import { Selectable } from 'kysely';
import { AssetExifTable } from 'src/schema/tables/asset-exif.table';
import { AssetExifLike } from 'test/factories/types';
import { factory } from 'test/small.factory';

export class AssetExifFactory {
  private constructor(private readonly value: Selectable<AssetExifTable>) {}

  static create(dto: AssetExifLike = {}) {
    return AssetExifFactory.from(dto).build();
  }

  static from(dto: AssetExifLike = {}) {
    return new AssetExifFactory({
      updatedAt: factory.date(),
      updateId: factory.uuid(),
      assetId: factory.uuid(),
      autoStackId: null,
      bitsPerSample: null,
      city: 'Austin',
      colorspace: null,
      country: 'United States of America',
      dateTimeOriginal: factory.date(),
      description: '',
      exifImageHeight: 420,
      exifImageWidth: 42,
      exposureTime: null,
      fileSizeInByte: 69,
      fNumber: 1.7,
      focalLength: 4.38,
      fps: null,
      iso: 947,
      latitude: 30.267_334_570_570_195,
      longitude: -97.789_833_534_282_07,
      lensModel: null,
      livePhotoCID: null,
      make: 'Google',
      model: 'Pixel 7',
      modifyDate: factory.date(),
      orientation: '1',
      profileDescription: null,
      projectionType: null,
      rating: 4,
      lockedProperties: [],
      state: 'Texas',
      tags: ['parent/child'],
      timeZone: 'UTC-6',

      // Extra & Brand-Specific EXIF fields
      actionsDescription: null,
      actionsSoftwareAgentName: null,
      afAreaMode: null,
      afAreaModeSetting: null,
      afMode: null,
      afPointPosition: null,
      afSubjectDetection: null,
      ambientTemperature: null,
      autoISO: null,
      brightness: null,
      cameraTemperature: null,
      cameraType: null,
      canonExposureMode: null,
      claimGeneratorInfoName: null,
      clarity: null,
      colorChromeEffect: null,
      colorChromeFXBlue: null,
      colorTempKelvin: null,
      colorTemperature: null,
      colorTone: null,
      continuousDrive: null,
      contrast: null,
      creatorTool: null,
      customRendered: null,
      developmentDynamicRange: null,
      driveMode: null,
      dynamicRange: null,
      electronicFrontCurtainShutter: null,
      exifVersion: null,
      exposureCompensation: null,
      exposureMode: null,
      exposureProgram: null,
      facesDetected: null,
      fade: null,
      fileFormat: null,
      filmMode: null,
      flash: null,
      flashAction: null,
      focusLocation: null,
      focusMode: null,
      focusMode2: null,
      focusPixel: null,
      grainEffectRoughness: null,
      grainEffectSize: null,
      highlightTone: null,
      highlights: null,
      historySoftwareAgent: null,
      imageQuality: null,
      imageStabilization: null,
      jpegQuality: null,
      lut1Name: null,
      lut1Opacity: null,
      lut2Name: null,
      lut2Opacity: null,
      meteringMode: null,
      monochromeGrainEffect: null,
      mpImageLength: null,
      noiseReduction: null,
      numberOfImages: null,
      pictureEffect: null,
      pictureMode: null,
      pictureStyle: null,
      pitchAngle: null,
      quality: null,
      releaseMode: null,
      rollAngle: null,
      saturation: null,
      sceneCaptureType: null,
      sensitivityType: null,
      shadowTone: null,
      shadows: null,
      sharpness: null,
      sharpnessRange: null,
      shootingMode: null,
      shutter: null,
      shutterType: null,
      software: null,
      userComment: null,
      wbShiftAB: null,
      wbShiftGM: null,
      whiteBalance: null,
      whiteBalanceFineTune: null,
      ...dto,
    });
  }

  build() {
    return { ...this.value };
  }
}
