import { createZodDto } from 'nestjs-zod';
import { Exif } from 'src/database';
import { MaybeDehydrated } from 'src/types';
import { asDateTimeString } from 'src/utils/date';
import z from 'zod';

export const ExifResponseSchema = z
  .object({
    make: z.string().nullish().default(null).describe('Camera make'),
    model: z.string().nullish().default(null).describe('Camera model'),
    exifImageWidth: z.int().min(0).nullish().default(null).describe('Image width in pixels'),
    exifImageHeight: z.int().min(0).nullish().default(null).describe('Image height in pixels'),
    fileSizeInByte: z.int().min(0).nullish().default(null).describe('File size in bytes'),
    orientation: z.string().nullish().default(null).describe('Image orientation'),
    // TODO: use `isoDatetimeToDate` when using `ZodSerializerDto` on the controllers.
    dateTimeOriginal: z.string().meta({ format: 'date-time' }).nullish().default(null).describe('Original date/time'),
    // TODO: use `isoDatetimeToDate` when using `ZodSerializerDto` on the controllers.
    modifyDate: z.string().meta({ format: 'date-time' }).nullish().default(null).describe('Modification date/time'),
    timeZone: z.string().nullish().default(null).describe('Time zone'),
    lensModel: z.string().nullish().default(null).describe('Lens model'),
    fNumber: z.number().nullish().default(null).describe('F-number (aperture)'),
    focalLength: z.number().nullish().default(null).describe('Focal length in mm'),
    iso: z.int().nullish().default(null).describe('ISO sensitivity'),
    exposureTime: z.string().nullish().default(null).describe('Exposure time'),
    latitude: z.number().nullish().default(null).describe('GPS latitude'),
    longitude: z.number().nullish().default(null).describe('GPS longitude'),
    city: z.string().nullish().default(null).describe('City name'),
    state: z.string().nullish().default(null).describe('State/province name'),
    country: z.string().nullish().default(null).describe('Country name'),
    description: z.string().nullish().default(null).describe('Image description'),
    projectionType: z.string().nullish().default(null).describe('Projection type'),
    rating: z.int().min(1).max(5).nullish().default(null).describe('Rating'),

    // Extra & Brand-Specific EXIF fields
    actionsDescription: z.string().nullish().default(null).describe('Actions description'),
    actionsSoftwareAgentName: z.string().nullish().default(null).describe('Actions software agent name'),
    afAreaMode: z.string().nullish().default(null).describe('AF area mode'),
    afAreaModeSetting: z.string().nullish().default(null).describe('AF area mode setting'),
    afMode: z.string().nullish().default(null).describe('AF mode'),
    afPointPosition: z.string().nullish().default(null).describe('AF point position'),
    afSubjectDetection: z.string().nullish().default(null).describe('AF subject detection'),
    ambientTemperature: z.string().nullish().default(null).describe('Ambient temperature'),
    autoISO: z.string().nullish().default(null).describe('Auto ISO'),
    brightness: z.string().nullish().default(null).describe('Brightness'),
    cameraTemperature: z.string().nullish().default(null).describe('Camera temperature'),
    cameraType: z.string().nullish().default(null).describe('Camera type'),
    canonExposureMode: z.string().nullish().default(null).describe('Canon exposure mode'),
    claimGeneratorInfoName: z.string().nullish().default(null).describe('Claim generator info name'),
    clarity: z.string().nullish().default(null).describe('Clarity'),
    colorChromeEffect: z.string().nullish().default(null).describe('Color chrome effect'),
    colorChromeFXBlue: z.string().nullish().default(null).describe('Color chrome FX blue'),
    colorTempKelvin: z.string().nullish().default(null).describe('Color temperature in Kelvin'),
    colorTemperature: z.string().nullish().default(null).describe('Color temperature'),
    colorTone: z.string().nullish().default(null).describe('Color tone'),
    continuousDrive: z.string().nullish().default(null).describe('Continuous drive mode'),
    contrast: z.string().nullish().default(null).describe('Contrast'),
    creatorTool: z.string().nullish().default(null).describe('Creator tool'),
    customRendered: z.string().nullish().default(null).describe('Custom rendered'),
    developmentDynamicRange: z.string().nullish().default(null).describe('Development dynamic range'),
    driveMode: z.string().nullish().default(null).describe('Drive mode'),
    dynamicRange: z.string().nullish().default(null).describe('Dynamic range'),
    electronicFrontCurtainShutter: z.string().nullish().default(null).describe('Electronic front curtain shutter'),
    exifVersion: z.string().nullish().default(null).describe('EXIF version'),
    exposureCompensation: z.string().nullish().default(null).describe('Exposure compensation'),
    exposureMode: z.string().nullish().default(null).describe('Exposure mode'),
    exposureProgram: z.string().nullish().default(null).describe('Exposure program'),
    facesDetected: z.string().nullish().default(null).describe('Faces detected'),
    fade: z.string().nullish().default(null).describe('Fade'),
    fileFormat: z.string().nullish().default(null).describe('File format'),
    filmMode: z.string().nullish().default(null).describe('Film mode'),
    flash: z.string().nullish().default(null).describe('Flash'),
    flashAction: z.string().nullish().default(null).describe('Flash action'),
    focusLocation: z.string().nullish().default(null).describe('Focus location'),
    focusMode: z.string().nullish().default(null).describe('Focus mode'),
    focusMode2: z.string().nullish().default(null).describe('Focus mode 2'),
    focusPixel: z.string().nullish().default(null).describe('Focus pixel'),
    grainEffectRoughness: z.string().nullish().default(null).describe('Grain effect roughness'),
    grainEffectSize: z.string().nullish().default(null).describe('Grain effect size'),
    highlightTone: z.string().nullish().default(null).describe('Highlight tone'),
    highlights: z.string().nullish().default(null).describe('Highlights'),
    historySoftwareAgent: z.string().nullish().default(null).describe('History software agent'),
    imageQuality: z.string().nullish().default(null).describe('Image quality'),
    imageStabilization: z.string().nullish().default(null).describe('Image stabilization'),
    jpegQuality: z.string().nullish().default(null).describe('JPEG quality'),
    lut1Name: z.string().nullish().default(null).describe('LUT 1 name'),
    lut1Opacity: z.string().nullish().default(null).describe('LUT 1 opacity'),
    lut2Name: z.string().nullish().default(null).describe('LUT 2 name'),
    lut2Opacity: z.string().nullish().default(null).describe('LUT 2 opacity'),
    meteringMode: z.string().nullish().default(null).describe('Metering mode'),
    monochromeGrainEffect: z.string().nullish().default(null).describe('Monochrome grain effect'),
    mpImageLength: z.string().nullish().default(null).describe('MP image length'),
    noiseReduction: z.string().nullish().default(null).describe('Noise reduction'),
    numberOfImages: z.string().nullish().default(null).describe('Number of images'),
    pictureEffect: z.string().nullish().default(null).describe('Picture effect'),
    pictureMode: z.string().nullish().default(null).describe('Picture mode'),
    pictureStyle: z.string().nullish().default(null).describe('Picture style'),
    pitchAngle: z.string().nullish().default(null).describe('Pitch angle'),
    quality: z.string().nullish().default(null).describe('Quality'),
    releaseMode: z.string().nullish().default(null).describe('Release mode'),
    rollAngle: z.string().nullish().default(null).describe('Roll angle'),
    saturation: z.string().nullish().default(null).describe('Saturation'),
    sceneCaptureType: z.string().nullish().default(null).describe('Scene capture type'),
    sensitivityType: z.string().nullish().default(null).describe('Sensitivity type'),
    shadowTone: z.string().nullish().default(null).describe('Shadow tone'),
    shadows: z.string().nullish().default(null).describe('Shadows'),
    sharpness: z.string().nullish().default(null).describe('Sharpness'),
    sharpnessRange: z.string().nullish().default(null).describe('Sharpness range'),
    shootingMode: z.string().nullish().default(null).describe('Shooting mode'),
    shutter: z.string().nullish().default(null).describe('Shutter'),
    shutterType: z.string().nullish().default(null).describe('Shutter type'),
    software: z.string().nullish().default(null).describe('Software'),
    userComment: z.string().nullish().default(null).describe('User comment'),
    wbShiftAB: z.string().nullish().default(null).describe('White balance shift AB'),
    wbShiftGM: z.string().nullish().default(null).describe('White balance shift GM'),
    whiteBalance: z.string().nullish().default(null).describe('White balance'),
    whiteBalanceFineTune: z.string().nullish().default(null).describe('White balance fine tune'),
  })
  .describe('EXIF response')
  .meta({ id: 'ExifResponseDto' });

class ExifResponseDto extends createZodDto(ExifResponseSchema) {}

export function mapExif(entity: MaybeDehydrated<Exif>): ExifResponseDto {
  return {
    make: entity.make,
    model: entity.model,
    exifImageWidth: entity.exifImageWidth,
    exifImageHeight: entity.exifImageHeight,
    fileSizeInByte: entity.fileSizeInByte ? Number.parseInt(entity.fileSizeInByte.toString()) : null,
    orientation: entity.orientation,
    dateTimeOriginal: asDateTimeString(entity.dateTimeOriginal),
    modifyDate: asDateTimeString(entity.modifyDate),
    timeZone: entity.timeZone,
    lensModel: entity.lensModel,
    fNumber: entity.fNumber,
    focalLength: entity.focalLength,
    iso: entity.iso,
    exposureTime: entity.exposureTime,
    latitude: entity.latitude,
    longitude: entity.longitude,
    city: entity.city,
    state: entity.state,
    country: entity.country,
    description: entity.description,
    projectionType: entity.projectionType,
    rating: entity.rating,

    // Extra & Brand-Specific EXIF fields
    actionsDescription: entity.actionsDescription,
    actionsSoftwareAgentName: entity.actionsSoftwareAgentName,
    afAreaMode: entity.afAreaMode,
    afAreaModeSetting: entity.afAreaModeSetting,
    afMode: entity.afMode,
    afPointPosition: entity.afPointPosition,
    afSubjectDetection: entity.afSubjectDetection,
    ambientTemperature: entity.ambientTemperature,
    autoISO: entity.autoISO,
    brightness: entity.brightness,
    cameraTemperature: entity.cameraTemperature,
    cameraType: entity.cameraType,
    canonExposureMode: entity.canonExposureMode,
    claimGeneratorInfoName: entity.claimGeneratorInfoName,
    clarity: entity.clarity,
    colorChromeEffect: entity.colorChromeEffect,
    colorChromeFXBlue: entity.colorChromeFXBlue,
    colorTempKelvin: entity.colorTempKelvin,
    colorTemperature: entity.colorTemperature,
    colorTone: entity.colorTone,
    continuousDrive: entity.continuousDrive,
    contrast: entity.contrast,
    creatorTool: entity.creatorTool,
    customRendered: entity.customRendered,
    developmentDynamicRange: entity.developmentDynamicRange,
    driveMode: entity.driveMode,
    dynamicRange: entity.dynamicRange,
    electronicFrontCurtainShutter: entity.electronicFrontCurtainShutter,
    exifVersion: entity.exifVersion,
    exposureCompensation: entity.exposureCompensation,
    exposureMode: entity.exposureMode,
    exposureProgram: entity.exposureProgram,
    facesDetected: entity.facesDetected,
    fade: entity.fade,
    fileFormat: entity.fileFormat,
    filmMode: entity.filmMode,
    flash: entity.flash,
    flashAction: entity.flashAction,
    focusLocation: entity.focusLocation,
    focusMode: entity.focusMode,
    focusMode2: entity.focusMode2,
    focusPixel: entity.focusPixel,
    grainEffectRoughness: entity.grainEffectRoughness,
    grainEffectSize: entity.grainEffectSize,
    highlightTone: entity.highlightTone,
    highlights: entity.highlights,
    historySoftwareAgent: entity.historySoftwareAgent,
    imageQuality: entity.imageQuality,
    imageStabilization: entity.imageStabilization,
    jpegQuality: entity.jpegQuality,
    lut1Name: entity.lut1Name,
    lut1Opacity: entity.lut1Opacity,
    lut2Name: entity.lut2Name,
    lut2Opacity: entity.lut2Opacity,
    meteringMode: entity.meteringMode,
    monochromeGrainEffect: entity.monochromeGrainEffect,
    mpImageLength: entity.mpImageLength,
    noiseReduction: entity.noiseReduction,
    numberOfImages: entity.numberOfImages,
    pictureEffect: entity.pictureEffect,
    pictureMode: entity.pictureMode,
    pictureStyle: entity.pictureStyle,
    pitchAngle: entity.pitchAngle,
    quality: entity.quality,
    releaseMode: entity.releaseMode,
    rollAngle: entity.rollAngle,
    saturation: entity.saturation,
    sceneCaptureType: entity.sceneCaptureType,
    sensitivityType: entity.sensitivityType,
    shadowTone: entity.shadowTone,
    shadows: entity.shadows,
    sharpness: entity.sharpness,
    sharpnessRange: entity.sharpnessRange,
    shootingMode: entity.shootingMode,
    shutter: entity.shutter,
    shutterType: entity.shutterType,
    software: entity.software,
    userComment: entity.userComment,
    wbShiftAB: entity.wbShiftAB,
    wbShiftGM: entity.wbShiftGM,
    whiteBalance: entity.whiteBalance,
    whiteBalanceFineTune: entity.whiteBalanceFineTune,
  };
}
