import { Kysely, sql } from 'kysely';

export async function up(db: Kysely<any>): Promise<void> {
  await sql`ALTER TABLE "asset_exif" 
    ADD COLUMN "afAreaMode" character varying,
    ADD COLUMN "afPointPosition" character varying,
    ADD COLUMN "afSubjectDetection" character varying,
    ADD COLUMN "autoISO" character varying,
    ADD COLUMN "brightness" character varying,
    ADD COLUMN "cameraTemperature" character varying,
    ADD COLUMN "cameraType" character varying,
    ADD COLUMN "canonExposureMode" character varying,
    ADD COLUMN "clarity" character varying,
    ADD COLUMN "colorChromeEffect" character varying,
    ADD COLUMN "colorChromeFXBlue" character varying,
    ADD COLUMN "colorTempKelvin" character varying,
    ADD COLUMN "colorTemperature" character varying,
    ADD COLUMN "colorTone" character varying,
    ADD COLUMN "continuousDrive" character varying,
    ADD COLUMN "contrast" character varying,
    ADD COLUMN "driveMode" character varying,
    ADD COLUMN "exifVersion" character varying,
    ADD COLUMN "exposureCompensation" character varying,
    ADD COLUMN "exposureMode" character varying,
    ADD COLUMN "exposureProgram" character varying,
    ADD COLUMN "facesDetected" character varying,
    ADD COLUMN "fileFormat" character varying,
    ADD COLUMN "filmMode" character varying,
    ADD COLUMN "focusLocation" character varying,
    ADD COLUMN "focusMode" character varying,
    ADD COLUMN "focusMode2" character varying,
    ADD COLUMN "focusPixel" character varying,
    ADD COLUMN "highlightTone" character varying,
    ADD COLUMN "highlights" character varying,
    ADD COLUMN "imageQuality" character varying,
    ADD COLUMN "imageStabilization" character varying,
    ADD COLUMN "jpegQuality" character varying,
    ADD COLUMN "lut1Name" character varying,
    ADD COLUMN "lut1Opacity" character varying,
    ADD COLUMN "lut2Name" character varying,
    ADD COLUMN "lut2Opacity" character varying,
    ADD COLUMN "meteringMode" character varying,
    ADD COLUMN "monochromeGrainEffect" character varying,
    ADD COLUMN "noiseReduction" character varying,
    ADD COLUMN "pictureEffect" character varying,
    ADD COLUMN "pictureMode" character varying,
    ADD COLUMN "pictureStyle" character varying,
    ADD COLUMN "pitchAngle" character varying,
    ADD COLUMN "quality" character varying,
    ADD COLUMN "rollAngle" character varying,
    ADD COLUMN "saturation" character varying,
    ADD COLUMN "sensitivityType" character varying,
    ADD COLUMN "shadowTone" character varying,
    ADD COLUMN "shadows" character varying,
    ADD COLUMN "sharpness" character varying,
    ADD COLUMN "shootingMode" character varying,
    ADD COLUMN "shutterType" character varying,
    ADD COLUMN "wbShiftAB" character varying,
    ADD COLUMN "wbShiftGM" character varying,
    ADD COLUMN "whiteBalance" character varying,
    ADD COLUMN "whiteBalanceFineTune" character varying;`.execute(db);
}

export async function down(db: Kysely<any>): Promise<void> {
  await sql`ALTER TABLE "asset_exif" 
    DROP COLUMN "afAreaMode",
    DROP COLUMN "afPointPosition",
    DROP COLUMN "afSubjectDetection",
    DROP COLUMN "autoISO",
    DROP COLUMN "brightness",
    DROP COLUMN "cameraTemperature",
    DROP COLUMN "cameraType",
    DROP COLUMN "canonExposureMode",
    DROP COLUMN "clarity",
    DROP COLUMN "colorChromeEffect",
    DROP COLUMN "colorChromeFXBlue",
    DROP COLUMN "colorTempKelvin",
    DROP COLUMN "colorTemperature",
    DROP COLUMN "colorTone",
    DROP COLUMN "continuousDrive",
    DROP COLUMN "contrast",
    DROP COLUMN "driveMode",
    DROP COLUMN "exifVersion",
    DROP COLUMN "exposureCompensation",
    DROP COLUMN "exposureMode",
    DROP COLUMN "exposureProgram",
    DROP COLUMN "facesDetected",
    DROP COLUMN "fileFormat",
    DROP COLUMN "filmMode",
    DROP COLUMN "focusLocation",
    DROP COLUMN "focusMode",
    DROP COLUMN "focusMode2",
    DROP COLUMN "focusPixel",
    DROP COLUMN "highlightTone",
    DROP COLUMN "highlights",
    DROP COLUMN "imageQuality",
    DROP COLUMN "imageStabilization",
    DROP COLUMN "jpegQuality",
    DROP COLUMN "lut1Name",
    DROP COLUMN "lut1Opacity",
    DROP COLUMN "lut2Name",
    DROP COLUMN "lut2Opacity",
    DROP COLUMN "meteringMode",
    DROP COLUMN "monochromeGrainEffect",
    DROP COLUMN "noiseReduction",
    DROP COLUMN "pictureEffect",
    DROP COLUMN "pictureMode",
    DROP COLUMN "pictureStyle",
    DROP COLUMN "pitchAngle",
    DROP COLUMN "quality",
    DROP COLUMN "rollAngle",
    DROP COLUMN "saturation",
    DROP COLUMN "sensitivityType",
    DROP COLUMN "shadowTone",
    DROP COLUMN "shadows",
    DROP COLUMN "sharpness",
    DROP COLUMN "shootingMode",
    DROP COLUMN "shutterType",
    DROP COLUMN "wbShiftAB",
    DROP COLUMN "wbShiftGM",
    DROP COLUMN "whiteBalance",
    DROP COLUMN "whiteBalanceFineTune";`.execute(db);
}
